Django-MQTT/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
]

Django-MQTT/city/urls.py
from django.urls import path
from .views import *

app_name = 'city'

urlpatterns = [
    path('index/', index, name='index'),
    path('add/', add, name='add'),
    path('update/<str:slug>', update, name='update'),
    path('delete/<str:slug>', delete, name='delete'),
]

Django-MQTT/home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', home_view, name='home'),
]

Django-MQTT/weather/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('city/', include('city.urls')),
    path('accounts/', include('accounts.urls')),
]

Django-MQTT/home/models.py
from django.db import models

# Create your models here.

Django-MQTT/home/views.py
from django.shortcuts import render


def home_view(request):
    return render(request, 'home.html', {})

Django-MQTT/templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Django-MQTT-Electron</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home:home' %}">City</a>
                <ul class="navbar-nav ml-auto">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'city:index' %}">Cities</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a></li>
                        {% if request.user.is_superuser %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'city:add' %}">Add City</a></li>
                        {% endif %}
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:register' %}">Register</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        {% block content %}
        {% endblock %}

        <!-- Bootstrap core JS-->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'scripts.js' %}"></script>
    </body>
</html>

Django-MQTT/templates/home.html
{% extends 'base.html'%}

{% block content %}

{% load static %}

    &nbsp;
    <div id="city-items" class="container">
        <p>
        	<b>
        		Welcome
        	</b>
        </p>
    </div>

{% endblock %}