Django-MQTT/city/urls.py
from django.urls import path
from .views import *

app_name = 'city'

urlpatterns = [
    path('index/', index, name='index'),
    path('add/', add, name='add'),
    path('update/<str:slug>', update, name='update'),
    path('delete/<str:slug>', delete, name='delete'),
]

Django-MQTT/weather/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('city/', include('city.urls')),
    path('accounts/', include('accounts.urls')),
]

Django-MQTT/city/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class City(models.Model):
    city = models.CharField(max_length=100, unique=True)
    temperature = models.IntegerField()
    condition = models.TextField()
    slug = models.SlugField(unique=True, editable=False, max_length=130)

    def __str__(self):
        return self.city

    def get_update_url(self):
        return reverse('city:update', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('city:delete', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.city)
        return super(City, self).save(*args, **kwargs)

Django-MQTT/city/forms.py
from django import forms
from .models import City


class CityForm(forms.ModelForm):

    class Meta:
        model = City
        fields = [
            'city',
            'temperature',
            'condition',
        ]

Django-MQTT/city/views.py
from django.shortcuts import render, get_object_or_404, redirect, Http404
from .models import City
from .forms import CityForm

import time

import paho.mqtt.client as mqtt

error_404_delay = 15

broker = 'raspberrypi'
port = 1883

index_client = add_client = update_client = delete_client = None


def on_message(client, userdata, msg):
    global index_client, add_client, update_client, delete_client
    print(msg.topic + " " + msg.payload.decode("utf-8"))
    if msg.topic == 'index/client':
        index_client = msg.payload.decode("utf-8")
    elif msg.topic == 'add/client':
        add_client = msg.payload.decode("utf-8")
    elif msg.topic == 'update/client':
        update_client = msg.payload.decode("utf-8")
    elif msg.topic == 'delete/client':
        delete_client = msg.payload.decode("utf-8")


client = mqtt.Client()

client.on_message = on_message
client.connect(broker, port)
client.subscribe('index/client')
client.subscribe('add/client')
client.subscribe('update/client')
client.subscribe('delete/client')

client.loop_start()


def index(request):
    if request.user.is_authenticated:
        global index_client, client

        client.publish('index/connected', 'connected')

        t_end = time.time() + error_404_delay
        while time.time() < t_end:
            if index_client is not None:
                break

        if index_client is not None:
            cities = list(reversed(City.objects.all()))
            index_client = None

            context = {
                'cities': cities,
                'user': request.user.username,
                'user_permission': request.user.is_superuser,
            }

            return render(request, 'city/index.html', context)
        else:
            raise Http404()
    else:
        raise Http404()


def add(request):
    if request.user.is_superuser:
        global add_client, client

        client.publish('add/connected', 'connected')

        t_end = time.time() + error_404_delay
        while time.time() < t_end:
            if add_client is not None:
                break

        if add_client is not None:
            form = CityForm(request.POST or None)
            add_client = None

            context = {
                'form': form,
                'user': request.user.username
            }

            return render(request, 'city/form.html', context)
        else:
            raise Http404()
    else:
        raise Http404()


def update(request, slug):
    if request.user.is_superuser:
        global update_client, client

        client.publish('update/connected', f'connected,{slug}')

        t_end = time.time() + error_404_delay
        while time.time() < t_end:
            if update_client is not None:
                break

        if update_client is not None:
            city = get_object_or_404(City, slug=slug)
            form = CityForm(request.POST or None, instance=city)
            update_client = None

            context = {
                'city': city,
                'form': form,
                'user': request.user.username
            }

            return render(request, 'city/form.html', context)
        else:
            raise Http404()
    else:
        raise Http404()


def delete(request, slug):
    if request.user.is_superuser:
        global delete_client, client

        client.publish('delete/connected', f'connected,{slug}')

        t_end = time.time() + error_404_delay
        while time.time() < t_end:
            if delete_client is not None:
                break

        if delete_client is not None:
            delete_client = None
            return redirect('city:index')
        else:
            raise Http404()
    else:
        raise Http404()

Django-MQTT/templates/city/form.html
{% extends 'base.html'%}

{% block content %}

{% load static %}

<div class="container" xmlns="http://www.w3.org/1999/html">
        &nbsp;
        <form id="form" method="POST">
            {% csrf_token %}

            {{ form.as_p }}

            <button id="save" class="btn btn-primary" type="submit">Save</button>
            {% if city %}
                <button id="delete" class="btn btn-primary" type="button"><a id="delete_link" href="{{city.get_delete_url}}" style="color:white">Delete</a></button>
            {% endif %}
        </form>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.js" type="text/javascript"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        var client;
		var host = "raspberrypi";
		var port = 9001;

		var loc = window.location
		var action = loc.pathname.split('/')[2]
        var formData = $("#form")
        var cityData = $("#id_city")
        var temperatureData = $("#id_temperature")
        var conditionData = $("#id_condition")
        var deleteLink = $('#delete_link')

        function onConnect() {
            console.log('connected')
			client.subscribe("update/client");
			client.subscribe("add/client");
			client.subscribe("index/client");
		}

		function onMessageArrived(message) {
		    console.log(message.destinationName + " -> " + message.payloadString)
            if(message.destinationName !== 'index/client' && message.payloadString.split(',')[0] == "done") {
                window.location.href = loc.origin + "/city/index/"
            }
            else if(message.destinationName == 'index/client' && message.payloadString.split(',')[0] == "update") {
                post_variables = message.payloadString.split(',')
                cityData.eq(0).val(post_variables[1])
                temperatureData.eq(0).val(post_variables[2])
                conditionData.eq(0).val(post_variables[3])
                document.getElementById(deleteLink).innerHTML = post_variables[6];
            }
        }

		function mqttConnect() {
			console.log("connecting to " + host + " "+ port);
			client = new Paho.MQTT.Client(host, port, "{{ user }}");
			client.onMessageArrived = onMessageArrived;

			var options = {

				timeout: 3,
				onSuccess: onConnect
			};

			client.connect(options);
		}

        mqttConnect();

        formData.submit(function(event) {
            event.preventDefault()
            var cityText = cityData.eq(0).val()
            var temperatureText = temperatureData.eq(0).val()
            var conditionText = conditionData.eq(0).val()
            console.log(`${cityText},${temperatureText},${conditionText}`)

            message = new Paho.MQTT.Message(`${cityText},${temperatureText},${conditionText}`);
			if(action == 'add') {
			    message.destinationName = "add/new-city";
			} else {
                message.destinationName = "update/done";
			}

			client.send(message);
        })
    </script>

{% endblock %}

Django-MQTT/templates/city/index.html
{% extends 'base.html'%}

{% block content %}

{% load static %}

    &nbsp;
    <div id="city-items" class="container">
        {% for city in cities %}
            <h1 id={{city.city}} class="mt-3">
                {{ city.city }}: {{ city.temperature }} °C, {{ city.condition }}
                &nbsp;
                {% if request.user.is_superuser %}
                    <button style='font-size:30px'>
                        <a href="{{ city.get_update_url }}" style="color:black">
                            <i class='fa fa-edit'></i>
                        </a>
                    </button>
                {% endif %}
            </h1>
        {% endfor %}
    </div>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.js" type="text/javascript"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        var client;
		var host = "raspberrypi";
		var port = 9001;

		var loc = window.location
        var cityHolder = $("#city-items")

		function onConnect() {
		    console.log('connected')
			client.subscribe("index/client");
            console.log("{{ user }}");
		}

        function onMessageArrived(message) {
            console.log(message.payloadString)
            post_variables = message.payloadString.split(',')
            if(post_variables[0] == "add") {
                cityData = post_variables[1]
                temperatureData = post_variables[2]
                conditionData = post_variables[3]
                city_part = cityData + ": " + temperatureData + " °C, " + conditionData
                space_part =  " &nbsp; "
                button_part = "<button style='font-size:30px'> <a href=" + `${loc.origin}${post_variables[4]}` + " style='color:black'><i class='fa fa-edit'></i></a></button>";
                if("{{ user_permission }}" == "True") {
                    added_city = "<h1 id=" + cityData + " class='mt-3'>" + city_part + space_part + button_part + "</h1>"
                } else {
                    added_city = "<h1 id=" + cityData + " class='mt-3'>" + city_part + space_part + "</h1>"
                }
                cityHolder.prepend(added_city)
            }
            else if(post_variables[0] == "update") {
                cityData = post_variables[1]
                temperatureData = post_variables[2]
                conditionData = post_variables[3]
                city_part = cityData + ": " + temperatureData + " °C, " + conditionData
                space_part =  " &nbsp; "
                button_part = "<button style='font-size:30px'> <a href=" + `${loc.origin}${post_variables[4]}` + " style='color:black'><i class='fa fa-edit'></i></a></button>";
                document.getElementById(post_variables[5]).id = cityData
                if("{{ user_permission }}" == "True") {
                    document.getElementById(cityData).innerHTML = city_part + space_part + button_part;
                } else {
                    document.getElementById(cityData).innerHTML = city_part + space_part;
                }
            }
            else if(post_variables[0] == "delete") {
                cityData = post_variables[1]
                document.getElementById(cityData).innerHTML = "";
            }
        }

        function onConnectionLost(responseObject) {
            console.log("disconnected: " + responseObject.errorMessage);
        }

		function mqttConnect() {
			console.log("connecting to " + host + " " + port);
			client = new Paho.MQTT.Client(host, port, "{{ user }}");
			client.onMessageArrived = onMessageArrived;
			client.onConnectionLost = onConnectionLost;

			var options = {
				onSuccess: onConnect
			};

			client.connect(options);
		}

        mqttConnect();
    </script>

{% endblock %}